language: node_js
sudo: false
jobs:
  include
    - stage: test
    script:
      - gulp test
    after_success:
      - npm install codecov codacy-coverage
      - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
    addons:
      srcclr: true
    node_js:
      - '6'
      - '7'
      - '8'
    cache: yarn
  include:
    - stage: staging
      if: branch = master-test
      script:
      - cd $TRAVIS_BUILD_DIR
      - chmod +x ./staging.sh
      - sh ./staging.sh
